---
- hosts: cloudlab
  become: yes

  tasks:
    - name: Stop old container
      shell: docker rm -f cloudlab-app || true
      ignore_errors: yes

    - name: Pull latest image
      shell: docker pull cloudlabacr12345.azurecr.io/cloudlab-app:v1

    - name: Run container
      shell: |
        docker run -d \
        --name cloudlab-app \
        -p 80:80 \
        cloudlabacr12345.azurecr.io/cloudlab-app:v1m