name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name cloudlabacr12345

      - name: Build Image
        run: |
          docker build -t cloudlabacr12345.azurecr.io/cloudlab-app:${{ github.sha }} .
          docker tag cloudlabacr12345.azurecr.io/cloudlab-app:${{ github.sha }} cloudlabacr12345.azurecr.io/cloudlab-app:latest

      - name: Push Image
        run: |
          docker push cloudlabacr12345.azurecr.io/cloudlab-app:${{ github.sha }}
          docker push cloudlabacr12345.azurecr.io/cloudlab-app:latest